- name: remove mysql
  hosts: localhost
  gather_facts: false
  tasks:
    - name: docker compose down
      community.docker.docker_compose_v2:
        project_src: .
        files:
        - mysql-adminer.yml
        state: absent
    - name: Remove mysql-client
      ansible.builtin.package:
        name: mysql-client
        state: absent
      become: yes
