name: Mysql actions demo
run-name: ${{ github.actor }} is testing out Mysql GitHub Actions 🚀
on: [push]

jobs:
  setup_mysql_database:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: rootpass
          MYSQL_DATABASE: subscribersdb
          MYSQL_USER: flywayuser
          MYSQL_PASSWORD: flywaypass
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install MySQL client
        run: sudo apt-get update && sudo apt-get install -y mysql-client

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL..."
          until mysqladmin ping -h 127.0.0.1 -uroot -prootpass --silent; do
            sleep 2
          done

      - name: Download Flyway CLI
        run: |
          curl -L https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/9.22.2/flyway-commandline-9.22.2-linux-x64.tar.gz | tar xvz

      - name: Run Flyway repair (resolve checksum)
        run: |
          cd flyway-9.22.2
          ./flyway -url=jdbc:mysql://127.0.0.1:3306/subscribersdb?allowPublicKeyRetrieval=true\&useSSL=false \
                   -user=flywayuser \
                   -password=flywaypass \
                   -locations=filesystem:../flyway/sql \
                   repair

      - name: Run Flyway migrate (V1 + V2)
        run: |
          cd flyway-9.22.2
          ./flyway -url=jdbc:mysql://127.0.0.1:3306/subscribersdb?allowPublicKeyRetrieval=true\&useSSL=false \
                   -user=flywayuser \
                   -password=flywaypass \
                   -locations=filesystem:../flyway/sql \
                   migrate

      - name: ✅ Deployment Done
        run: echo "🎉 All Flyway migrations completed successfully!"

      - name: Install dependencies for testing
        run: pip install mysql-connector-python

      - name: Run unit tests
        run: python3 -m unittest discover -s tests
